version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATEBASE: root
    ports:
      - '3306:3306'
  portfolio_2:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/portfolio_2
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    tty: true
    stdin_open: true
